---
- name: "Install git"
  ansible.builtin.package:
    name: "git"
    state: "present"
  tags:
    - packages
    - desktop
    - webserver

- name: Link gitattributes file
  ansible.builtin.file:
    src: "{{ role_path }}/files/gitattributes_global.link"
    dest: "~/.gitattributes_global"
    state: link
    force: true
  tags:
    - config
    - desktop

- name: Check if gitconfig exists
  ansible.builtin.stat:
    path: "~/.gitconfig"
  register: gitconfig_stat
  tags:
    - config
    - desktop
    - webserver

- name: Back up gitconfig
  ansible.builtin.command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "~/.gitconfig.bak"
  when: gitconfig_stat.stat.exists
  tags:
    - config
    - desktop
    - webserver

- name: Make sure gitconfig is up to date
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "~/.gitconfig"
    mode: 0644
  tags:
    - config
    - desktop
    - webserver
